version: '3'
services:
  client:
    image: 'alantrinh/multi-client'
    mem_limit: 128m
    hostname: client
  server:
    image: 'alantrinh/multi-server'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=multi-docker-redis.o3dajw.ng.0001.use1.cache.amazonaws.com
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=multi-docker-postgres.caffdngjasgd.us-east-1.rds.amazonaws.com
      - PGDATABASE=fibvalues
      - PGPASSWORD=postgrespassword
      - PGPORT=5432
  worker:
    image: 'alantrinh/multi-worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=multi-docker-redis.o3dajw.ng.0001.use1.cache.amazonaws.com
      - REDIS_PORT=6379
  nginx:
    image: 'alantrinh/multi-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'